config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :projects, except: [:show]
  get 'ios-projects', to: 'projects#ios'
  get 'project/:id', to: 'projects#show', as: 'project_show'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda {|attrs| attrs['name'].blank?}

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.ios
    where(subtitle: 'iOS App')
  end

  scope :ruby_on_rails, -> {where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project_item, only: [:edit, :show, :update, :destroy]
  layout 'project'
  access all: [:show, :index, :ios], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @project_items = Project.all
  end

  def ios
    @ios_project_items = Project.ios
  end

  def new
    @project_item = Project.new
    3.times { @project_item.technologies.build }
  end

  def create
    @project_item = Project.new(project_params)

    respond_to do |format|
      if @project_item.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @project_item.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    
  end

  def destroy
    @project_item.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully removed.' }
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, 
                                    :subtitle, 
                                    :body, 
                                    technologies_attributes:[:name]
                                    )
  end

  def set_project_item
    @project_item = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project_item) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_item.html.erb
<h3><%= link_to project_item.title, project_show_path(project_item) %></h3>

<p><%= project_item.subtitle %></p>

<p><%= project_item.body %></p>

<%= image_tag project_item.thumb_image unless project_item.thumb_image.nil?%>
<%= link_to "Edit", edit_project_path(project_item) if logged_in?(:site_admin) %>
<%= link_to 'Delete', project_path(project_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>

app/views/projects/edit.html.erb
<h1> Edit this project item</h1>


<%= render 'form', project_item: @project_item %>

app/views/projects/index.html.erb
<h1>Project Items</h1>

<%= link_to "Create New Item", new_project_path if logged_in?(:site_admin) %>

<%= render partial: 'project_item', collection: @project_items %>

app/views/projects/ios.html.erb
<h1>Project Items</h1>

<%= link_to "Create New Item", new_project_path if logged_in?(:site_admin) %>

<% @ios_project_items.each do |project_item| %>
  <h3><%= link_to project_item.title, project_show_path(project_item) %></h3>
  <p><%= project_item.subtitle %></p>
  <p><%= project_item.body %></p>
  <%= image_tag project_item.thumb_image unless project_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_project_path(project_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete', project_path(project_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>
<% end %>

app/views/projects/new.html.erb
<h1> Create a new project item</h1>

<%= render 'form', project_item: @project_item %>

app/views/projects/show.html.erb
<%= image_tag @project_item.main_image %>
<h1><%= @project_item.title %></h1>

<em><%= @project_item.subtitle %></em>

<p><%= @project_item.body %></p>

<h2>Technologies Used: </h2>

<% @project_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>